# name: Code Analysis

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - '**'

# jobs:
#   sonarqube:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: SonarQube Scan
#         env:
#           SONAR_HOST: ${{ secrets.SONAR_HOST }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: |
#           npm install -g sonarqube-scanner
#           sonar-scanner \
#             -Dsonar.host.url=${{ env.SONAR_HOST }} \
#             -Dsonar.token=${{ env.SONAR_TOKEN }} \
#             -Dsonar.projectKey=node_mongo_crud
