name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: http://192.168.31.156:9000
          SONAR_LOGIN: squ_3f2979f274c5e58030440ab0aaebdce23c063a6d
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner
